version: '3'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cyp2:/var/lib/postgresql/data
    ports:
      - "${PORT_PG}:5432"

  telemirror:
    image: sybernorth/mirror_yelp
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      SESSION_STRING: ${SESSION_STRING}
      USE_MEMORY_DB: "true"
      CHAT_MAPPING: ${CHAT_MAPPING}
      LOG_LEVEL: ${LOG_LEVEL}
      REPEAT_INTERVAL: ${REPEAT_INTERVAL}
      REPEAT_COUNT: ${REPEAT_COUNT}
    env_file:
      - .env
    volumes:
      - ./.configs:/app/.configs:ro
    ports:
      - "${PORT_API}:8000"
    depends_on:
      - postgres

volumes:
  cyp2: